### ISSUE TITLE
training

### ISSUE THREAD

**Issue by huangmengxiao000** [frederickszk/LRNet#23]
Hello, I would like to ask, how many landmarks are used for each video during training? Is all the landmarks extracted from each frame of each video used for training? Is it continuous frames? If not, it is discarded Or continue to use/whether to take the first N frames/whether to randomly take N frames. That is to say, during training, what are the rules for selecting landmarks from each video?

**Comment by frederickszk** [comment]
We use 30 continuous frames as a single training sample. 
For example, if a video has 303 frames, it would be cut into 10 sample (each of them contains 30 continuous frames), and last 3 frames would be dropped. 
We prefer not to randomly select N frames, because of the possibility of artificially introducing discontinuities.
Our latest updated model weights (PyTorch version) are trained with this setting.

**Comment by huangmengxiao000** [comment]
Thank you sir, I understand
